### ISSUE TITLE
Installing yaup project may use the wrong artifact GAV.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/yaup#1]
Installing the project when not using the default project name causes artifact install to generate the wrong artifact name.

In the situation a user clones the project with a different working directory then the artifact adopts that name as well.

This is an issue for me when trying to use the project as a dependency.

**Comment by willr3** [comment]
The project now publishes to maven so I suspect this is no longer an issue. Please re-open if that is incorrect
